<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
/**
* Run the database seeds.
*
* @return void
*/
public function run()
{
	// DB::table('country')->delete();
	$countries = array(
		array('id' => 1, 'country_name' => "Afghanistan"),
		array('id' => 2, 'country_name' => "Albania"),
		array('id' => 3, 'country_name' => "Algeria"),
		array('id' => 4, 'country_name' => "American Samoa"),
		array('id' => 5, 'country_name' => "Andorra"),
		array('id' => 6, 'country_name' => "Angola"),
		array('id' => 7, 'country_name' => "Anguilla"),
		array('id' => 8, 'country_name' => "Antarctica"),
		array('id' => 9, 'country_name' => "Antigua And Barbuda"),
		array('id' => 10, 'country_name' => "Argentina"),
		array('id' => 11, 'country_name' => "Armenia"),
		array('id' => 12, 'country_name' => "Aruba"),
		array('id' => 13, 'country_name' => "Australia"),
		array('id' => 14, 'country_name' => "Austria"),
		array('id' => 15, 'country_name' => "Azerbaijan"),
		array('id' => 16, 'country_name' => "Bahamas The"),
		array('id' => 17, 'country_name' => "Bahrain"),
		array('id' => 18, 'country_name' => "Bangladesh"),
		array('id' => 19, 'country_name' => "Barbados"),
		array('id' => 20, 'country_name' => "Belarus"),
		array('id' => 21, 'country_name' => "Belgium"),
		array('id' => 22, 'country_name' => "Belize"),
		array('id' => 23, 'country_name' => "Benin"),
		array('id' => 24, 'country_name' => "Bermuda"),
		array('id' => 25, 'country_name' => "Bhutan"),
		array('id' => 26, 'country_name' => "Bolivia"),
		array('id' => 27, 'country_name' => "Bosnia and Herzegovina"),
		array('id' => 28, 'country_name' => "Botswana"),
		array('id' => 29, 'country_name' => "Bouvet Island"),
		array('id' => 30, 'country_name' => "Brazil"),
		array('id' => 31, 'country_name' => "British Indian Ocean Territory"),
		array('id' => 32, 'country_name' => "Brunei"),
		array('id' => 33, 'country_name' => "Bulgaria"),
		array('id' => 34, 'country_name' => "Burkina Faso"),
		array('id' => 35, 'country_name' => "Burundi"),
		array('id' => 36, 'country_name' => "Cambodia"),
		array('id' => 37, 'country_name' => "Cameroon"),
		array('id' => 38, 'country_name' => "Canada"),
		array('id' => 39, 'country_name' => "Cape Verde"),
		array('id' => 40, 'country_name' => "Cayman Islands"),
		array('id' => 41, 'country_name' => "Central African Republic"),
		array('id' => 42, 'country_name' => "Chad"),
		array('id' => 43, 'country_name' => "Chile"),
		array('id' => 44, 'country_name' => "China"),
		array('id' => 45, 'country_name' => "Christmas Island"),
		array('id' => 46, 'country_name' => "Cocos (Keeling) Islands"),
		array('id' => 47, 'country_name' => "Colombia"),
		array('id' => 48, 'country_name' => "Comoros"),
		array('id' => 49, 'country_name' => "Congo"),
		array('id' => 50, 'country_name' => "Congo The Democratic Republic Of The"),
		array('id' => 51, 'country_name' => "Cook Islands"),
		array('id' => 52, 'country_name' => "Costa Rica"),
		array('id' => 53, 'country_name' => "Cote D Ivoire (Ivory Coast)"),
		array('id' => 54, 'country_name' => "Croatia (Hrvatska)"),
		array('id' => 55, 'country_name' => "Cuba"),
		array('id' => 56, 'country_name' => "Cyprus"),
		array('id' => 57, 'country_name' => "Czech Republic"),
		array('id' => 58, 'country_name' => "Denmark"),
		array('id' => 59, 'country_name' => "Djibouti"),
		array('id' => 60, 'country_name' => "Dominica"),
		array('id' => 61, 'country_name' => "Dominican Republic"),
		array('id' => 62, 'country_name' => "East Timor"),
		array('id' => 63, 'country_name' => "Ecuador"),
		array('id' => 64, 'country_name' => "Egypt"),
		array('id' => 65, 'country_name' => "El Salvador"),
		array('id' => 66, 'country_name' => "Equatorial Guinea"),
		array('id' => 67, 'country_name' => "Eritrea"),
		array('id' => 68, 'country_name' => "Estonia"),
		array('id' => 69, 'country_name' => "Ethiopia"),
		array('id' => 70, 'country_name' => "External Territories of Australia"),
		array('id' => 71, 'country_name' => "Falkland Islands"),
		array('id' => 72, 'country_name' => "Faroe Islands"),
		array('id' => 73, 'country_name' => "Fiji Islands"),
		array('id' => 74, 'country_name' => "Finland"),
		array('id' => 75, 'country_name' => "France"),
		array('id' => 76, 'country_name' => "French Guiana"),
		array('id' => 77, 'country_name' => "French Polynesia"),
		array('id' => 78, 'country_name' => "French Southern Territories"),
		array('id' => 79, 'country_name' => "Gabon"),
		array('id' => 80, 'country_name' => "Gambia The"),
		array('id' => 81, 'country_name' => "Georgia"),
		array('id' => 82, 'country_name' => "Germany"),
		array('id' => 83, 'country_name' => "Ghana"),
		array('id' => 84, 'country_name' => "Gibraltar"),
		array('id' => 85, 'country_name' => "Greece"),
		array('id' => 86, 'country_name' => "Greenland"),
		array('id' => 87, 'country_name' => "Grenada"),
		array('id' => 88, 'country_name' => "Guadeloupe"),
		array('id' => 89, 'country_name' => "Guam"),
		array('id' => 90, 'country_name' => "Guatemala"),
		array('id' => 91, 'country_name' => "Guernsey and Alderney"),
		array('id' => 92, 'country_name' => "Guinea"),
		array('id' => 93, 'country_name' => "Guinea-Bissau"),
		array('id' => 94, 'country_name' => "Guyana"),
		array('id' => 95, 'country_name' => "Haiti"),
		array('id' => 96, 'country_name' => "Heard and McDonald Islands"),
		array('id' => 97, 'country_name' => "Honduras"),
		array('id' => 98, 'country_name' => "Hong Kong S.A.R."),
		array('id' => 99, 'country_name' => "Hungary"),
		array('id' => 100, 'country_name' => "Iceland"),
		array('id' => 101, 'country_name' => "India"),
		array('id' => 102, 'country_name' => "Indonesia"),
		array('id' => 103, 'country_name' => "Iran"),
		array('id' => 104, 'country_name' => "Iraq"),
		array('id' => 105, 'country_name' => "Ireland"),
		array('id' => 106, 'country_name' => "Israel"),
		array('id' => 107, 'country_name' => "Italy"),
		array('id' => 108, 'country_name' => "Jamaica"),
		array('id' => 109, 'country_name' => "Japan"),
		array('id' => 110, 'country_name' => "Jersey"),
		array('id' => 111, 'country_name' => "Jordan"),
		array('id' => 112, 'country_name' => "Kazakhstan"),
		array('id' => 113, 'country_name' => "Kenya"),
		array('id' => 114, 'country_name' => "Kiribati"),
		array('id' => 115, 'country_name' => "Korea North"),
		array('id' => 116, 'country_name' => "Korea South"),
		array('id' => 117, 'country_name' => "Kuwait"),
		array('id' => 118, 'country_name' => "Kyrgyzstan"),
		array('id' => 119, 'country_name' => "Laos"),
		array('id' => 120, 'country_name' => "Latvia"),
		array('id' => 121, 'country_name' => "Lebanon"),
		array('id' => 122, 'country_name' => "Lesotho"),
		array('id' => 123, 'country_name' => "Liberia"),
		array('id' => 124, 'country_name' => "Libya"),
		array('id' => 125, 'country_name' => "Liechtenstein"),
		array('id' => 126, 'country_name' => "Lithuania"),
		array('id' => 127, 'country_name' => "Luxembourg"),
		array('id' => 128, 'country_name' => "Macau S.A.R."),
		array('id' => 129, 'country_name' => "Macedonia"),
		array('id' => 130, 'country_name' => "Madagascar"),
		array('id' => 131, 'country_name' => "Malawi"),
		array('id' => 132, 'country_name' => "Malaysia"),
		array('id' => 133, 'country_name' => "Maldives"),
		array('id' => 134, 'country_name' => "Mali"),
		array('id' => 135, 'country_name' => "Malta"),
		array('id' => 136, 'country_name' => "Man (Isle of)"),
		array('id' => 137, 'country_name' => "Marshall Islands"),
		array('id' => 138, 'country_name' => "Martinique"),
		array('id' => 139, 'country_name' => "Mauritania"),
		array('id' => 140, 'country_name' => "Mauritius"),
		array('id' => 141, 'country_name' => "Mayotte"),
		array('id' => 142, 'country_name' => "Mexico"),
		array('id' => 143, 'country_name' => "Micronesia"),
		array('id' => 144, 'country_name' => "Moldova"),
		array('id' => 145, 'country_name' => "Monaco"),
		array('id' => 146, 'country_name' => "Mongolia"),
		array('id' => 147, 'country_name' => "Montserrat"),
		array('id' => 148, 'country_name' => "Morocco"),
		array('id' => 149, 'country_name' => "Mozambique"),
		array('id' => 150, 'country_name' => "Myanmar"),
		array('id' => 151, 'country_name' => "Namibia"),
		array('id' => 152, 'country_name' => "Nauru"),
		array('id' => 153, 'country_name' => "Nepal"),
		array('id' => 154, 'country_name' => "Netherlands Antilles"),
		array('id' => 155, 'country_name' => "Netherlands The"),
		array('id' => 156, 'country_name' => "New Caledonia"),
		array('id' => 157, 'country_name' => "New Zealand"),
		array('id' => 158, 'country_name' => "Nicaragua"),
		array('id' => 159, 'country_name' => "Niger"),
		array('id' => 160, 'country_name' => "Nigeria"),
		array('id' => 161, 'country_name' => "Niue"),
		array('id' => 162, 'country_name' => "Norfolk Island"),
		array('id' => 163, 'country_name' => "Northern Mariana Islands"),
		array('id' => 164, 'country_name' => "Norway"),
		array('id' => 165, 'country_name' => "Oman"),
		array('id' => 166, 'country_name' => "Pakistan"),
		array('id' => 167, 'country_name' => "Palau"),
		array('id' => 168, 'country_name' => "Palestinian Territory Occupied"),
		array('id' => 169, 'country_name' => "Panama"),
		array('id' => 170, 'country_name' => "Papua new Guinea"),
		array('id' => 171, 'country_name' => "Paraguay"),
		array('id' => 172, 'country_name' => "Peru"),
		array('id' => 173, 'country_name' => "Philippines"),
		array('id' => 174, 'country_name' => "Pitcairn Island"),
		array('id' => 175, 'country_name' => "Poland"),
		array('id' => 176, 'country_name' => "Portugal"),
		array('id' => 177, 'country_name' => "Puerto Rico"),
		array('id' => 178, 'country_name' => "Qatar"),
		array('id' => 179, 'country_name' => "Reunion"),
		array('id' => 180, 'country_name' => "Romania"),
		array('id' => 181, 'country_name' => "Russia"),
		array('id' => 182, 'country_name' => "Rwanda"),
		array('id' => 183, 'country_name' => "Saint Helena"),
		array('id' => 184, 'country_name' => "Saint Kitts And Nevis"),
		array('id' => 185, 'country_name' => "Saint Lucia"),
		array('id' => 186, 'country_name' => "Saint Pierre and Miquelon"),
		array('id' => 187, 'country_name' => "Saint Vincent And The Grenadines"),
		array('id' => 188, 'country_name' => "Samoa"),
		array('id' => 189, 'country_name' => "San Marino"),
		array('id' => 190, 'country_name' => "Sao Tome and Principe"),
		array('id' => 191, 'country_name' => "Saudi Arabia"),
		array('id' => 192, 'country_name' => "Senegal"),
		array('id' => 193, 'country_name' => "Serbia"),
		array('id' => 194, 'country_name' => "Seychelles"),
		array('id' => 195, 'country_name' => "Sierra Leone"),
		array('id' => 196, 'country_name' => "Singapore"),
		array('id' => 197, 'country_name' => "Slovakia"),
		array('id' => 198, 'country_name' => "Slovenia"),
		array('id' => 199, 'country_name' => "Smaller Territories of the UK"),
		array('id' => 200, 'country_name' => "Solomon Islands"),
		array('id' => 201, 'country_name' => "Somalia"),
		array('id' => 202, 'country_name' => "South Africa"),
		array('id' => 203, 'country_name' => "South Georgia"),
		array('id' => 204, 'country_name' => "South Sudan"),
		array('id' => 205, 'country_name' => "Spain"),
		array('id' => 206, 'country_name' => "Sri Lanka"),
		array('id' => 207, 'country_name' => "Sudan"),
		array('id' => 208, 'country_name' => "Suricountry_name"),
		array('id' => 209, 'country_name' => "Svalbard And Jan Mayen Islands"),
		array('id' => 210, 'country_name' => "Swaziland"),
		array('id' => 211, 'country_name' => "Sweden"),
		array('id' => 212, 'country_name' => "Switzerland"),
		array('id' => 213, 'country_name' => "Syria"),
		array('id' => 214, 'country_name' => "Taiwan"),
		array('id' => 215, 'country_name' => "Tajikistan"),
		array('id' => 216, 'country_name' => "Tanzania"),
		array('id' => 217, 'country_name' => "Thailand"),
		array('id' => 218, 'country_name' => "Togo"),
		array('id' => 219, 'country_name' => "Tokelau"),
		array('id' => 220, 'country_name' => "Tonga"),
		array('id' => 221, 'country_name' => "Trinidad And Tobago"),
		array('id' => 222, 'country_name' => "Tunisia"),
		array('id' => 223, 'country_name' => "Turkey"),
		array('id' => 224, 'country_name' => "Turkmenistan"),
		array('id' => 225, 'country_name' => "Turks And Caicos Islands"),
		array('id' => 226, 'country_name' => "Tuvalu"),
		array('id' => 227, 'country_name' => "Uganda"),
		array('id' => 228, 'country_name' => "Ukraine"),
		array('id' => 229, 'country_name' => "United Arab Emirates"),
		array('id' => 230, 'country_name' => "United Kingdom"),
		array('id' => 231, 'country_name' => "United States"),
		array('id' => 232, 'country_name' => "United States Minor Outlying Islands"),
		array('id' => 233, 'country_name' => "Uruguay"),
		array('id' => 234, 'country_name' => "Uzbekistan"),
		array('id' => 235, 'country_name' => "Vanuatu"),
		array('id' => 236, 'country_name' => "Vatican City State (Holy See)"),
		array('id' => 237, 'country_name' => "Venezuela"),
		array('id' => 238, 'country_name' => "Vietnam"),
		array('id' => 239, 'country_name' => "Virgin Islands (British)"),
		array('id' => 240, 'country_name' => "Virgin Islands (US)"),
		array('id' => 241, 'country_name' => "Wallis And Futuna Islands"),
		array('id' => 242, 'country_name' => "Western Sahara"),
		array('id' => 243, 'country_name' => "Yemen"),
		array('id' => 244, 'country_name' => "Yugoslavia"),
		array('id' => 245, 'country_name' => "Zambia"),
		array('id' => 246, 'country_name' => "Zimbabwe"),
		);
		DB::table('country')->insert($countries);
	}
}
